"""Ajustar clave foránea en HistorialBusqueda

Revision ID: 8f193ff13ef3
Revises: 
Create Date: 2024-09-11 15:20:28.841337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f193ff13ef3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_busqueda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('busqueda', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.alter_column('comentario',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               nullable=False)
        batch_op.drop_index('fk_usuarios_has_motos_motos1_idx')
        batch_op.drop_index('fk_usuarios_has_motos_usuarios1_idx')

    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.drop_column('logo')

    with op.batch_alter_table('motos', schema=None) as batch_op:
        batch_op.drop_index('fk_motos_usuarios1_idx')
        batch_op.drop_index('fk_repuestos_marca1_idx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motos', schema=None) as batch_op:
        batch_op.create_index('fk_repuestos_marca1_idx', ['marca_id'], unique=False)
        batch_op.create_index('fk_motos_usuarios1_idx', ['usuarios_id'], unique=False)

    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', mysql.VARCHAR(length=200), nullable=True))

    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.create_index('fk_usuarios_has_motos_usuarios1_idx', ['idUsuarios'], unique=False)
        batch_op.create_index('fk_usuarios_has_motos_motos1_idx', ['idMotos'], unique=False)
        batch_op.alter_column('comentario',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               nullable=True)

    op.drop_table('historial_busqueda')
    # ### end Alembic commands ###
